- stage: deployProd
  jobs:
  - job: approveRelease # use manual validation task to approve release
    timeoutInMinutes: 4320 # timeout in 3 days  
    pool: server  # where it going to be executed
    steps:
    - task: ManualValidation@1
      timeoutInMinutes: 1440 # task time out in 1 day
      inputs:
        notifyUser: 'user@mail.at'
        instruction: 'Please validate deploy to prod'

  - job: deployProd
    steps:
    - task: DownloadSecureFile@1
      name: sshKey  # this task will download secure file and then you can refrence it as 'sshKey'
      inputs:
      secureFile: 'your_secure_file_name'
    - script: | # use pipe for multiline in yaml
        chmod 400 $(sshKey.secureFilePath)
        ssh -o StrictHostKeyChecking=no -i $(sshKey.secureFilePath) root@machine_ip "
          docker ps -aq | xargs docker stop | xargs docker rm && 
          docker run -d -p 8080:80 $(IMAGE_REPO)/$(IMAGE_REPO):$(TAG)"
