trigger:
- main  # it start pipeline on pushing on main branch

pool: # where the tasks will be executed 
  vmImage: 'ubuntu-latest' # like a runner, this machine run on cloud
  # our tasks will execut on a machine where ubuntu latest installed on it

variables:
  IMAGE_REGISTRY_CONNECTION: 'name_of_connection'
  IMAGE_REGISTRY: 'docker_registry_name'
  IMAGE_REPO: 'docker_repo_name'
  TAG: '$(Build.BuildId)'


stages: # higher most level
- stage: BuildApp
  jobs:
  - job: BuildPushImage
    steps: # steps are smallest units like running a script
    - task: Docker@2
      inputs:
        containerRegistry: '($IMAGE_REGISTRY_CONNECTION)'
        repository: '$(IMAGE_REPO)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(TAG)'

- stage: scanImage
  jobs:
  - job: scanImage
    steps:  # you can use default tasks of azure in this step
    - tasks: AzureCLI@2
      inputs: 
        azureSubscription: 'Azure'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: '$(Build.SourceDirectory)/scripts/path_to_script/script.bat'
        arguments: 'script_arguments'


#  deploy the service 
# use task: azure app service deploy
- stage: deployImage
  jobs:
  - job: deployImage
    steps: 
    - task: AzureRmWebApplicationDeployment@2
      inputs:
        ConnectionType: 'AzureRm'
        azureSubscription: 'Azure'
        appType: 'webAppContainer'
        WebAppName: 'app_name'
        DockerNameSpace: '$(IMAGE_REGISTRY)'
        DockerRepository: '$(IMAGE_REPO)'
        DockerImageTag: '$(TAG)'

      
      


